### ISSUE TITLE
handle the summery data

### ISSUE THREAD

**Issue by meeple142** [byuitechops/csv-mapleta-to-d2l#10]

**Comment by g-mips** [comment]
Can you provide me with a link to where I can find this data?

**Comment by meeple142** [comment]
just as a reminder for me what this is.
This is to handle if the csv in has the summery data on top  to remove it before parsing.

**Comment by meeple142** [comment]
here's the link you wanted
https://github.com/byuicampuscd/csv-mapleta-to-d2l/blob/master/forTesting/mapleTAOutTwoGroupsEverything.csv

**Comment by g-mips** [comment]
Summary Data is handled!
