### ISSUE TITLE
Remove student id column from output CSV and only username

### ISSUE THREAD

**Issue by meeple142** [byuitechops/csv-mapleta-to-d2l#13]

**Comment by g-mips** [comment]
Is this meaning from the original CSV file? Like if those columns were missing from the original CSV file?

The original CSV file being the maple exported from MapleTA.

**Comment by meeple142** [comment]
in the output file we do not need the OrgDefinedId column at all, no header or data.
lets do that.
:frog: :tiger2: :koala:

**Comment by meeple142** [comment]
and this one for good measure 
:hatched_chick:
