### ISSUE TITLE
what does it do with blank entries

### ISSUE THREAD

**Issue by meeple142** [byuitechops/csv-mapleta-to-d2l#17]
ignore 0's in MapleTA does it come in blank? `""` or `0`
and if `""` what does the converter do?

**Comment by meeple142** [comment]
meaning if the csv file that come in has `""` as one of the scores what does it do?

**Comment by g-mips** [comment]
Anything that isn't numeric will be ignored and thus the grade item's score will not be affected, in D2L. The handle for percentages needs to take into account that empty strings are a possibility and should reflect that the grade item's score will be not be affected.

This also means that when it tries to do math on said score, it needs to check if the string is blank first and handle that situation.

**Comment by g-mips** [comment]
Line 172 - 178 changed to this:

``` JavaScript
if (row[col.nameOld].indexOf('%') > -1) {
    rowOut[col.nameNew + ' Points Grade'] = (parseInt(row[col.nameOld], 10) / 100 * col.pointsPossible).toFixed(2);
} else if (row[col.nameOld].length == 0) {
    rowOut[col.nameNew + ' Points Grade'] = "";
} else {
    throw new Error("CSV file contains number scores and not percentages");
}
```

No other changes were necessary.
