### ISSUE TITLE
check to see if all the grade assignment names are unique

### ISSUE THREAD

**Issue by meeple142** [byuitechops/csv-mapleta-to-d2l#21]
Then throw an error

**Comment by meeple142** [comment]
This is talking about the valence call in my sandbox some how I got to grade items with the same name. I think it has something to do with SCORM and how d2l will make you grade item if you don't assign one

**Comment by meeple142** [comment]
wrong button

**Comment by g-mips** [comment]
Do we care if the "shortNames" are the same as well or just "name"?

**Comment by g-mips** [comment]
This is done except for the question i asked and will modify the error message with Autumn.

**Comment by g-mips** [comment]
This is handled!

**Comment by meeple142** [comment]
Humm that’s a good question. We don’t use it at all and the D2L CSV in doesn’t use it as far as I have seen so I think we are ok not checking it.
