### ISSUE TITLE
make a separate licences file and put in github and in equella

### ISSUE THREAD

**Issue by meeple142** [byuitechops/csv-mapleta-to-d2l#23]

**Comment by meeple142** [comment]
need to have all the dependency library files 
off the top of my head
jquery and its one dependancy,
d3-dsv and its one dependancy
download.js
jsfilereader.js

There could be more

**Comment by g-mips** [comment]
Licenses are found in LICENSE.

They include: jquery, sizzle, d3-dsv, download, filereader, and rw.

**Comment by meeple142** [comment]
Can you add our licence too :smile: under a heading

##  Licence

Then a heading that says 

## Third Party Licences

also it is always nice to add in links to the libraries' web sites

Then remember to update Equella :grinning:  thank you
Here's a :cake: for your troubles
or is the :cake: a lie? :yum:

**Comment by g-mips** [comment]
What about for like rw? Do you want the NPM website or github website? Or both?

And yes the ![image](https://cloud.githubusercontent.com/assets/7365623/18099332/37246c0c-6ea3-11e6-9d08-4e22bee1cde3.png) was a lie :'( haha

EDIT: Wow that cake was huge. Not sure how you did the emojis haha

**Comment by g-mips** [comment]
Also, are we just using the MIT license?

**Comment by g-mips** [comment]
One last question, who are the copyright holders in this case?

**Comment by g-mips** [comment]
This is done except for knowing the answers to the questions I asked.

**Comment by g-mips** [comment]
:cake: Done
