### ISSUE TITLE
File name display

### ISSUE THREAD

**Issue by meeple142** [byuitechops/csv-mapleta-to-d2l#4]
I like that you maked the file name green but we need to make it fit the rest of the lay out. 

What do you think?

**Comment by g-mips** [comment]
I changed the background color to something not as blinding as white and make the file name a darker green. I think this will look a bit better. If you agree, go ahead and close this issue!

**Comment by meeple142** [comment]
slide up and add label

**Comment by g-mips** [comment]
Done!
