### ISSUE TITLE
The list of questions

### ISSUE THREAD

**Issue by meeple142** [byuitechops/csv-mapleta-to-d2l#5]
Adding the name to the end of each sentence works but its a lot to read on every line.

What if we made a table instead.

|  | All Grades1 | All Grades2 | All Grades3 |
| --- | --- | --- | --- |
| Bright Space Name |  |  |  |
| Points Possible |  |  |  |

Well that could get tricky with nice margins on the main div.

or just make a new table for every 3 columns or something

**Comment by g-mips** [comment]
Changed to this, however, swapped the columns with rows for more space.
